name       : udftools
version    : '2.2'
release    : 5
source     :
    - https://github.com/pali/udftools/releases/download/2.2/udftools-2.2.tar.gz : d67ce203d71d828619d6d3791ab33eefab4bc506e0ee73355ab6c2f91d52448e
license    : GPL-2.0-or-later
component  : system.utils
summary    : Linux UDF Filesystem userspace utilities
description: |
    Linux tools for UDF filesystems and DVD/CD-R(W) drives
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
