name       : udftools
version    : 2.0
release    : 1
source     :
    - https://github.com/pali/udftools/releases/download/2.0/udftools-2.0.tar.gz : 67fe428d452901215cfad8049d250540c97114b1a20dd63277b91c2c4fae8292
license    : GPL-2.0-only
component  : system.utils
summary    : Linux UDF Filesystem userspace utilities
description: |
    Linux tools for UDF filesystems and DVD/CD-R(W) drives
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-libdir-variable-in-pktsetup.patch

    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
